#!/bin/bash

echo "site:$1 \"ext:doc | ext:docx | ext:odt | ext:pdf\" filetype:password" 
echo "site:$1 \"ext:sql | ext:db\" intext:password" 
echo "site:$1 \"ext:config | ext:cnf | ext:reg | ext:inf\" intext:password" 
echo "site:$1 \"ext:asp | ext:aspx | ext:php | ext:jsp\" intext:password" 
echo "site:$1 \"ext:swf | ext:fla\" intext:password" 
echo "site:$1 \"ext:doc | ext:docx | ext:odt | ext:pdf\" intext:confidential" 
echo "site:$1 \"ext:xls | ext:xlsx | ext:csv\" intext:credit card" 
echo "site:$1 \"ext:ppt | ext:pptx | ext:odp\" intext:presentation" 
echo "site:$1 \"ext:doc | ext:docx | ext:odt | ext:pdf\" intext:proposal" 
echo "site:$1 \"ext:doc | ext:docx | ext:odt | ext:pdf\" intext:financial report"
echo "site:$1 ext:bkf | ext:bkp | ext:bak | ext:old | ext:backup" 
echo "site:$1 allintext:username filetype:log" 
echo "site:$1 inurl:/proc/self/cwd" 
echo "site:$1 \"index of\" \"database.sql.zip\"" 
echo "site:$1 inurl:admin \"@gmail.com\""  
echo "site:$1 inurl:zoom.us/j and intext:\"scheduled for\"" 
echo "site:$1 allintitle: restricted filetype:doc site:gov" 
echo "site:$1 intitle:\"Index of\" wp-admin" 