#!/bin/bash

echo "site:$1 \"ext:doc | ext:docx | ext:odt | ext:sxw | ext:pps | ext:rtf | ext:psw | ext:pdf\" filetype:password" 
echo "site:$1 \"ext:sql | ext:db | ext:dbf | ext:mdb\" intext:password" 
echo "site:$1 \"ext:config | ext:cnf | ext:reg | ext:inf\" intext:password" 
echo "site:$1 \"ext:asp | ext:aspx | ext:php | ext:jsp\" intext:password" 
echo "site:$1 \"ext:swf | ext:fla\" intext:password" 
echo "site:$1 \"ext:doc | ext:docx | ext:odt | ext:pdf\" intext:confidential" 
echo "site:$1 \"ext:xls | ext:xlsx | ext:csv\" intext:credit card" 
echo "site:$1 \"ext:ppt | ext:pptx | ext:odp\" intext:presentation" 
echo "site:$1 \"ext:doc | ext:docx | ext:odt | ext:pdf\" intext:proposal" 
echo "site:$1 \"ext:doc | ext:docx | ext:odt | ext:pdf\" intext:financial report"
echo "site:$1 ext:bkf | ext:bkp | ext:bak | ext:old | ext:backup" 
echo "site:$1 allintext:username filetype:log | ext:log"
echo "site:$1 filetype:log | ext:log" 
echo "site:$1 inurl:/proc/self/cwd" 
echo "site:$1 \"index of\" \"database.sql.zip\"" 
echo "site:$1 inurl:admin \"@gmail.com\""  
echo "site:$1 inurl:zoom.us/j and intext:\"scheduled for\"" 
echo "site:$1 allintitle: restricted filetype:doc site:gov" 
echo "site:$1 intitle:\"Index of\" wp-admin | intitle:index.of"
echo "site:$1 ext:xml | ext:conf | ext:cnf | ext:reg | ext:inf | ext:rdp | ext:cfg | ext:txt | ext:ora | ext:ini | ext:env"
echo "site:$1 inurl:login | inurl:signin | intitle:Login | intitle:"sign in" | inurl:auth "
echo "site:$1 inurl:signup | inurl:register | inurl:registration | intitle:registration | intitle:Signup | intitle:enroll | inurl:enroll"
echo "site:$1 inurl:password | credential | username filetype:log"
echo "site:$1 'not for distribution' | confidential | 'employee only' | proprietary | top secret | classified | trade secret | internal | private filetype:pdf"
echo "site:$1 'not for distribution' | confidential | 'employee only' | proprietary | top secret | classified | trade secret | internal | private | WS_FTP | ws_ftp | log | LOG filetype:log"
echo "site:$1 'not for distribution' | confidential | 'employee only' | proprietary | top secret | classified | trade secret | internal | private filetype:xls | filetype:csv | filetype:doc | filetype:txt"
echo "site:$1 intitle:administrator | intitle:debug | intitle:admin | intitle:root | intitle:wp-login | intitle:master | intitle:superuser "
echo "site:$1 inurl:administrator | inurl:debug | inurl:admin | inurl:root | inurl:wp-login | inurl:master | inurl:superuser"
echo "site:$1 intext:administrator | intext:debug | intext:admin | intext:root | intext:wp-login | intext:master | intext:superuser"
